### ISSUE TITLE
Improve warning when BOM and XML encoding attribute conflict

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-sgml#14]
I have an XML file with the following first line (notice the UTF-16 BOM):

```xml
<U+FEFF><?xml version="1.0" encoding="UTF-8" ?>
```

This is clearly a buggy file, but `sgml_parse/2` gives a warning that is quite misleading:

```
Warning: <FILE>:16:
	SGML2PL(sgml): []:1: #PCDATA ("ï»¿") not allowed here
```

Maybe the waning should be something like "Conflict between BOM and XML encoding attribute"?

**Comment by JanWielemaker** [comment]
The problem is that it doesn't get that far.  It enables UCS-2 (should be UTF-16) decoding and than 
the entire <?xml ... is no longer readable.  So, it just sees _CDATA_ and that is not allowed before the first element.   At a higher level you could retry bij seeking back to the start and change the encoding to a superset of ASCII (e.g., UTF-8) and try to see whether you get a sensible document opening.

**Comment by wouterbeek** [comment]
Ok, will try that one.  Thanks!
