### ISSUE TITLE
Space handling in SGML parser

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-sgml#3]
Option for space handling does not seem to have any effect on parsing SGML.

Reproducible example:
```prolog
?- [library(sgml)].
?- [library(http/http_open)].
?- IRI = 'https://lists.w3.org/Archives/Public/w3c-rdfcore-wg'.
?- load_structure($IRI, Dom, [space(preserve)]).
Dom = [element(html, [...], ['\n', ...
?- load_structure($IRI, Dom, [space(sgml)]).
Dom = [element(html, [...], ['\n', ...
?- load_structure($IRI, Dom, [space(default)]).
Dom = [element(html, [...], ['\n', ...
?- load_structure($IRI, Dom, [space(remove)]).
Dom = [element(html, [...], ['\n', ...
```

**Comment by JanWielemaker** [comment]
I think the crux is in "In XML mode, the mode is further controlled by the xml:space attribute, which may be specified both in the DTD and in the document.".  The document is xhtml.  It will load the
HTML DTD.  If I use `load_xml/3`, which will bypass the DTD detection, it nicely removes the white space.

**Comment by wouterbeek** [comment]
Thanks for clearing this up!

Since in this case the data is able to overrule an explicit setting in the user program, should the programmer not be informed about this with a warning message?  Is it easy to emit such a message?  (This is happening too deep into C code for me to assess.)

Cheers!

**Comment by JanWielemaker** [comment]
I don't know.  The space option sets a default for the outer element.  Inner elements may change
this.  I think that is a good idea because processing HTML in space(remove) is weird.  The option
is intended to simplify processing of XML documents that basically contain data structures.  Luckily
we have JSON for that these days.  XML is about annotating documents and there space generally
matters.
